service: <serviceName>-auth0 

provider:
  name: aws
  runtime: nodejs8.10
  stage: pro
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"


functions:
  authorizer:
    handler: index.handler
    environment:
      JWKS_URI: <jwks_uri>
      AUDIENCE: <audience>
      TOKEN_ISSUER: <token_issuer>